[package]
name = "carddealer"
version = "0.1.0"
authors = ["Pierre-Alexandre St-Jean <pa@stjean.me>"]

[dependencies]
rand = "0.5.5"
actix = "0.7.4"
actix-web = "0.7.4"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"