[package]
name = "carddealer"
version = "0.3.0"
authors = ["Pierre-Alexandre St-Jean <pa@stjean.me>"]
edition = "2018"

[dependencies]
rand = "0.8.4"
actix-web = "3.3"

serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
