[package]
name = "carddealer"
version = "0.2.0"
authors = ["Pierre-Alexandre St-Jean <pa@stjean.me>"]
edition = "2018"

[dependencies]
rand = "0.8.2"
actix-web = "3"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"